baseURL = 'https://ta.njunova.com/'
locale = 'zh-CN'
theme = "book"
defaultContentLanguage = "zh"
license = "CC BY-NC-SA 4.0"
hasCJKlanguage = true
enableGitInfo = true
publishDir = "../public"

[params]
    BookSearch = true
    BookTheme = 'light'
    BookTitle = "LEARNOVA文档"
    BookLogo = 'logo.svg'
    BookRepo = 'https://github.com/ShelfSeeck/Learnova-docs'
    BookDateFormat = 'January 2, 2006'

[markup]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.highlight]
        style = "github"


